defaults:
  - override hydra/job_logging: disabled
  - override hydra/hydra_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .

data:
  sdo_data_root_path: /nobackupnfs1/sroy14/processed_data/Helio/nc 
  train_data_path: ../data/surya-bench_sdo.csv
  valid_data_path: ../data/surya-bench_sdo.csv
  test_data_path: ../data/surya-bench_sdo.csv
  train_flare_data_path: ../data/surya-bench-flare-forecasting/C24w/train_C24w_24.csv
  valid_flare_data_path: ../data/surya-bench-flare-forecasting/C24w/val_C24w.csv
  leaky_valid_flare_data_path: ../data/surya-bench-flare-forecasting/C24w/leaky_val_C24w.csv
  test_flare_data_path: ../data/surya-bench-flare-forecasting/C24w/test_C24w.csv
  channels: ['aia94', 'aia131', 'aia171', 'aia193', 'aia211', 'aia304', 'aia335', 'aia1600', 'hmi_m', 'hmi_bx', 'hmi_by', 'hmi_bz', 'hmi_v']
  time_delta_input_minutes: [-60,0]
  time_delta_target_minutes: 0
  n_input_timestamps: 2 # must be equal to time_delta_input_minutes
  is_downstream: true
  batch_size: 1
  num_data_workers: 8
  pin_memory: true
  prefetch_factor: 2
  persistent_workers: true
  pooling: 1
  random_vert_flip: false
  scalers_path: ../data/scalers.yaml
  scalers: null
  class_names: ["FL", "NFL"]
  use_leaky_validation: false
  use_simplecache: true
  s3_cache_dir: /tmp/helio_s3_cache

backbone:
  model_name: resnet18 # resnet18, resnet34, resnet50, alexnet,
  in_channels: 13
  time_steps: 2
  num_classes: 1
  p_drop: 0.5
  threshold: 0.5
  log_step_size: 1
  time_embedding:
    type: linear
    time_dim: 2

classifier_metrics:
  task: 'binary'  # ["binary", "multiclass", "multilabel"]
  num_classes: 2
  average: 'macro'  # ["micro", "macro", "weighted", "none"]
  train_metrics_config:
    metrics_to_report: ['accuracy', 'precision', 'recall', 'f1']
  validation_metrics_config:
    metrics_to_report: ['accuracy', 'precision', 'recall', 'f1']

loss:
  type: focal 
  focal:
    alpha: 0.25
    gamma: 2.0
    reduction: mean

optimizer:
  type: adamw
  lr: 1e-5
  weight_decay: 0.5
  scheduler:
      use: cosine_warmup # The switch
      monitor: val_hss 
    
      # Define available strategies
      cosine_warmup:
        # T_max: 10
        # eta_min: 1e-6
        total_steps: 1000
        warmup_ratio: 0.1 # Default 10% warmup
      plateau:
        mode: min
        factor: 0.1
        patience: 10

etc:
  phase: train # test
  resume: false
  ckpt_dir: ../results/check_point/baselines/resnet18/daily_c/
  ckpt_name_tag: resnet18_daily_c
  ckpt_file: last.ckpt  
  ckpt_weights_only: false
  save_test_results_path: ../results/
  precision: bf16-mixed #16-mixed
  accelerator: gpu
  devices: 1 #[0, 1, 2, 3]
  num_nodes: 1
  strategy: auto #auto, ddp, fsdp
  max_epochs: 300
  limit_train_batches: null
  limit_val_batches: null
  accumulate_grad_batches: 64
  enable_version_counter: False

wandb:
  name: resnet18_daily_c_nasgh_new_wg
  id: resnet18_daily_c_nasgh_new_wg
  resume: allow
  save_dir: ../results
  entity: gsu-dmlab
  project: helio-fm
  log_model: false
  notes: resnet18
  offline: false
  save_code: false
  tag: ["resnet18", "C", "nasgh", "daily"] # backbone model, head type, task

use_latitude_in_learned_flow: false
loss_weights: [] # [] or list of weights per channel
rollout_steps: 0
num_mask_aia_channels: 0
drop_hmi_probability: 0.0
validate_after_epoch: 1
