#!/usr/bin/bash
#PBS -S /usr/bin/bash
#PBS -N test_surya_gh

#PBS -l select=1:ncpus=10:ngpus=1:mem=70GB:model=gh200
#PBS -q gpu_normal
#PBS -l walltime=24:00:00
#PBS -M jhong36@gsu.edu
#PBS -m abe
#PBS -W umask=002

echo "Changing directory to: $PBS_O_WORKDIR"
cd $PBS_O_WORKDIR

JOBID=$(echo "$PBS_JOBID" | cut -d. -f1)

exec >logs/test/test_surya_gh.${JOBID}.out
exec 2>logs/test/test_surya_gh.${JOBID}.err

mapfile -t NODES < <(sort -u "$PBS_NODEFILE")
if [[ ${#NODES[@]} -ne 1 ]]; then
  echo "ERROR: expected 1 node, got ${#NODES[@]}"
  exit 1
fi

source /nobackupp17/jhong15/miniforge3_gh/etc/profile.d/conda.sh
conda activate flare_surya

python scripts/finetuning/finetuning.py +surya=test_x_run
