# @package _global_

data:
  train_flare_data_path: ../data/surya-bench-flare-forecasting/C24w/train_C24w_freq24.csv
  valid_flare_data_path: ../data/surya-bench-flare-forecasting/C24w/val_C24w.csv
  leaky_valid_flare_data_path: ../data/surya-bench-flare-forecasting/C24w/leaky_val_C24w.csv
  test_flare_data_path: ../data/surya-bench-flare-forecasting/C24w/test_C24w.csv

backbone:
  pooling_type: attention_pooling

loss:
  type: focal
  cross_entropy:
    class_weights: [1.0, 1.0]
  focal:
    alpha: 0.5
    gamma: 0.99
    reduction: mean

optimizer:
  type: adamw
  lr: 1e-5
  weight_decay: 1e-3

etc:
  phase: train # test
  resume: false
  ckpt_dir: ../results/check_point/surya_flare/daily_c/
  ckpt_name_tag: mlp_daily_c_focal
  ckpt_file: last.ckpt
  ckpt_weights_only: false
  max_epochs: 50

wandb:
  name: mlp_daily_c_focal_nasgh_3
  id: mlp_daily_c_focal_nasgh_3
  resume: allow
  notes: "simple mlp head"
  offline: false
  tag: ["mlp", "C", "daily", "nasgh", "focal"] # backbone model, head type, task
