# @package _global_

data:
  train_flare_data_path: ../data/surya-bench-flare-forecasting/M24w/train_M24w_freq24.csv
  valid_flare_data_path: ../data/surya-bench-flare-forecasting/M24w/val_M24w.csv
  leaky_valid_flare_data_path: ../data/surya-bench-flare-forecasting/M24w/leaky_val_M24w.csv
  test_flare_data_path: ../data/surya-bench-flare-forecasting/M24w/test_M24w.csv

head:
  pooling_type: attention_pooling

loss:
  type: focal
  focal:
    alpha: 0.75
    gamma: 2.0
    reduction: mean

optimizer:
  type: adamw
  lr: 1e-5
  weight_decay: 1e-2

etc:
  phase: train # test
  resume: false
  ckpt_dir: ../results/check_point/surya_flare/daily_m/
  ckpt_name_tag: mlp_daily_m_focal
  ckpt_file: last.ckpt
  ckpt_weights_only: false

wandb:
  name: mlp_daily_m_focal_nasgh
  id: mlp_daily_m_focal_nasgh
  resume: allow
  notes: "simple mlp head"
  offline: false
  tag: ["mlp", "M", "daily", "nasgh", "focal"] # backbone model, head type, task

