# @package _global_

defaults:
  - override /hydra/job_logging: disabled
  - override /hydra/hydra_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .

data:
  train_flare_data_path: ./data/surya-bench-flare-forecasting/M24w/train_M24w_freq24.csv
  valid_flare_data_path: ./data/surya-bench-flare-forecasting/M24w/val_M24w.csv
  leaky_valid_flare_data_path: ./data/surya-bench-flare-forecasting/M24w/leaky_val_M24w.csv
  test_flare_data_path: ./data/surya-bench-flare-forecasting/M24w/test_M24w_freq4.csv
  apply_undersampling: false
  undersample_factor: 1
  seed: 1004

backbone:
  pooling_type: attention_pooling

etc:
  phase: test # test
  resume: true
  ckpt_dir: ./results/checkpoints/surya_flare/daily_m/
  ckpt_name_tag: mlp_daily_m_ce_nosample
  ckpt_file: mlp_daily_m_ce_nosample_lr0.00015_wd0.03_epoch=9.ckpt
  ckpt_weights_only: false
  save_test_results_path: ./results/surya_daily_m_ce_nosample.csv

wandb:
  name: mlp_daily_m_ce_nosample_nasgh_test
  id: mlp_daily_m_ce_nosample_nasgh_test
  resume: allow
  project: flareforecasting-nosampling-test
  group: surya
  offline: false
  notes: ""
  tag: ["mlp", "M", "daily", "nasgh", "cross_entropy", "nosampling"] # backbone model, head type, task
