# @package _global_

data:
  train_flare_data_path: ./data/surya-bench-flare-forecasting/C2w/train_C2w.csv
  valid_flare_data_path: ./data/surya-bench-flare-forecasting/C2w/val_C2w.csv
  leaky_valid_flare_data_path: ./data/surya-bench-flare-forecasting/C2w/leaky_val_C2w.csv
  test_flare_data_path: ./data/surya-bench-flare-forecasting/C2w/test_C2w_freq4.csv
  apply_undersampling: false
  undersample_factor: 1
  seed: 1004

backbone:
  pooling_type: attention_pooling

loss:
  type: cross_entropy
  cross_entropy:
    class_weights: [1.0, 2.0]
  focal:
    alpha: 0.25
    gamma: 2.0
    reduction: mean

etc:
  phase: test # test
  resume: true
  ckpt_dir: /nobackupnfs1/sroy14/heliofm/jinsu/checkpoints/surya/8hour_c2w/
  ckpt_name_tag: null
  ckpt_file: mlp_8hour_c2w_ce_nosample_lr0.00015_wd0.03_epoch=3.ckpt
  ckpt_weights_only: false
  save_test_results_path: ./results/test_results/surya_8hour_c2w_ce_nosample.csv

wandb:
  name: mlp_8hour_c2w_ce_nosample_nasgh_test
  id: mlp_8hour_c2w_ce_nosample_nasgh_test
  resume: allow
  project: flareforecasting-nosampling-test
  group: surya
  offline: false
  notes: ""
  tag: ["mlp", "C2w", "8hour", "nasgh", "cross_entropy", "nosampling"] # backbone model, head type, task
