# @package _global_

data:
  train_flare_data_path: ./data/surya-bench-flare-forecasting/C24w/train_C24w_freq4.csv
  valid_flare_data_path: ./data/surya-bench-flare-forecasting/C24w/val_C24w.csv
  leaky_valid_flare_data_path: ./data/surya-bench-flare-forecasting/C24w/leaky_val_C24w.csv
  test_flare_data_path: ./data/surya-bench-flare-forecasting/C24w/test_C24w.csv
  undersample_factor: 1
  seed: 1004

backbone:
  model_name: alexnet # resnet18, resnet34, resnet50, alexnet,

loss:
  type: cross_entropy
  cross_entropy:
    class_weights: [1.0, 1.0]
  focal:
    alpha: 0.5
    gamma: 0.99
    reduction: mean
    label_smoothing: 0.2

optimizer:
  type: adamw
  lr: 2e-4
  weight_decay: 1e-3

etc:
  phase: train # test
  resume: false
  ckpt_dir: ./results/checkpoints/baselines/alexnet/daily_c/
  ckpt_name_tag: alexnet_daily_c_ce_undersample
  ckpt_file: last.ckpt
  ckpt_weights_only: false
  max_epochs: 50

wandb:
  name: alexnet_daily_c_ce_undersample_nasgh
  id: alexnet_daily_c_ce_undersample_nasgh
  resume: allow
  notes: alexnet
  offline: false
  tag: ["alexnet", "C", "nasgh", "daily", "cross_entropy", "undersample"] # backbone model, head type, task
