# @package _global_

data:
  train_flare_data_path: ./data/surya-bench-flare-forecasting/M24w/train_M24w_freq24.csv
  valid_flare_data_path: ./data/surya-bench-flare-forecasting/M24w/val_M24w.csv
  leaky_valid_flare_data_path: ./data/surya-bench-flare-forecasting/M24w/leaky_val_M24w.csv
  test_flare_data_path: ./data/surya-bench-flare-forecasting/M24w/test_M24w_freq4.csv

backbone:
  model_name: alexnet # resnet18, resnet34, resnet50, alexnet,

loss:
  type: cross_entropy
  cross_entropy:
    class_weights: [1.0, 2.0]
  focal:
    alpha: 0.25
    gamma: 2.0
    reduction: mean

etc:
  phase: test # test
  resume: true
  ckpt_dir: ./results/checkpoints/baselines/alexnet/4hour_m/
  ckpt_name_tag: alexnet_4hour_m_ce_nosample
  ckpt_file: alexnet_4hour_m_ce_undersample_lr0.0001_wd0.001_epoch=5.ckpt
  ckpt_weights_only: false
  save_test_results_path: ./results/alexnet_m_4hour_test_result.csv

wandb:
  name: alexnet_4hour_m_nasgh_test
  id: alexnet_4hour_m_nasgh_test
  resume: allow
  project: flareforecasting-nosampling-test
  group: alexnet
  offline: false
  notes: ""
  tag: ["alexnet", "M", "nasgh", "4hour", "cross_entropy", "undersampling", "test"] # backbone model, head type, task
