# @package _global_

data:
  train_flare_data_path: ./data/surya-bench-flare-forecasting/M24w/train_M24w_freq24.csv
  valid_flare_data_path: ./data/surya-bench-flare-forecasting/M24w/val_M24w.csv
  leaky_valid_flare_data_path: ./data/surya-bench-flare-forecasting/M24w/leaky_val_M24w.csv
  test_flare_data_path: ./data/surya-bench-flare-forecasting/M24w/test_M24w.csv
  apply_undersampling: false
  undersample_factor: 1
  seed: 1004

backbone:
  model_name: alexnet # resnet18, resnet34, resnet50, alexnet,

loss:
  type: cross_entropy
  cross_entropy:
    class_weights: [1.0, 2.0]
  focal:
    alpha: 0.75
    gamma: 2.0
    reduction: mean
    label_smoothing: 0.2

optimizer:
  type: adamw
  lr: 1e-4
  weight_decay: 1e-3

etc:
  phase: train # test
  resume: false
  ckpt_dir: ./results/checkpoints/baselines/alexnet/daily_m/
  ckpt_name_tag: alexnet_daily_m_ce_nosample
  ckpt_file: alexnet_daily_m_ce_nosample_lr0.0001_wd0.001_alexnet_epoch=6-val_hss=0.0000.ckpt
  ckpt_weights_only: false
  max_epochs: 50

wandb:
  name: alexnet_daily_m_ce_nosample_nasgh
  id: alexnet_daily_m_ce_nosample_nasgh
  resume: allow
  project: flareforecasting-nosampling
  group: alexent
  notes: ""
  offline: false
  tag: ["alexnet", "M", "nasgh", "daily", "cross_entropy", "nosampling", "noclassweights"] # backbone model, head type, task
