# @package _global_

data:
  train_flare_data_path: ./data/surya-bench-flare-forecasting/C24w/train_C24w_freq24.csv
  valid_flare_data_path: ./data/surya-bench-flare-forecasting/C24w/val_C24w.csv
  leaky_valid_flare_data_path: ./data/surya-bench-flare-forecasting/C24w/leaky_val_C24w.csv
  test_flare_data_path: ./data/surya-bench-flare-forecasting/C24w/test_C24w_freq4.csv

backbone:
  model_name: alexnet # resnet18, resnet34, resnet50, alexnet,

loss:
  type: cross_entropy
  cross_entropy:
    class_weights: [1.0, 2.0]
  focal:
    alpha: 0.25
    gamma: 2.0
    reduction: mean

etc:
  phase: test # test
  resume: true
  ckpt_dir: ./results/checkpoints/baselines/alexnet/daily_c/
  ckpt_name_tag: alexnet_daily_c_ce_nosample
  ckpt_file: alexnet_daily_c_ce_nosample_lr0.0001_wd0.001_epoch=3.ckpt
  ckpt_weights_only: false
  save_test_results_path: ./results/alexnet_c_daily_test_result.csv

wandb:
  name: alexnet_daily_c_nasgh_test
  id: alexnet_daily_c_nasgh_test
  resume: allow
  project: flareforecasting-nosampling-test
  group: alexnet
  offline: false
  notes: ""
  tag: ["alexnet", "C", "nasgh", "daily", "cross_entropy", "nosampling", "test"] # backbone model, head type, task
