# @package _global_

data:
  train_flare_data_path: ./data/surya-bench-flare-forecasting/M2w/train_M2w_freq24.csv
  valid_flare_data_path: ./data/surya-bench-flare-forecasting/M2w/val_M2w.csv
  leaky_valid_flare_data_path: ./data/surya-bench-flare-forecasting/M2w/leaky_val_M2w.csv
  test_flare_data_path: ./data/surya-bench-flare-forecasting/M2w/test_M2w.csv
  apply_undersampling: false
  undersample_factor: 1
  seed: 1004

backbone:
  model_name: resnet18 # resnet18, resnet34, resnet50, alexnet,

loss:
  type: cross_entropy
  cross_entropy:
    class_weights: [1.0, 2.0]
  focal:
    alpha: 0.75
    gamma: 2.0
    reduction: mean
    label_smoothing: 0.2

optimizer:
  type: adamw
  lr: 1e-4
  weight_decay: 1e-2

etc:
  phase: train # test
  resume: false
  ckpt_dir: ./results/checkpoints/baselines/resnet18/daily_m2w/
  ckpt_name_tag: resnet18_daily_m2w_ce_nosample
  ckpt_file: null
  ckpt_weights_only: false
  max_epochs: 50

wandb:
  name: resnet18_daily_m2w_ce_nosample_nasgh
  id: resnet18_daily_m2w_ce_nosample_nasgh
  resume: allow
  project: flareforecasting-nosampling
  group: resnet18
  notes: ""
  offline: false
  tag: ["resnet18", "M2w", "nasgh", "daily", "cross_entropy", "nosampling"] # backbone model, head type, task
