# @package _global_

data:
  train_flare_data_path: ../data/surya-bench-flare-forecasting/X24w/train_X24w_freq4.csv
  valid_flare_data_path: ../data/surya-bench-flare-forecasting/X24w/val_X24w.csv
  leaky_valid_flare_data_path: ../data/surya-bench-flare-forecasting/X24w/leaky_val_X24w.csv
  test_flare_data_path: ../data/surya-bench-flare-forecasting/X24w/test_X24w.csv
  undersample_factor: 1
  seed: 1004

backbone:
  model_name: resnet18 # resnet18, resnet34, resnet50, alexnet,

loss:
  type: cross_entropy
  cross_entropy:
    class_weights: [1.0, 1.0]
  focal:
    alpha: 0.95
    gamma: 4.0
    reduction: mean
    label_smoothing: 0.2

optimizer:
  type: adamw
  lr: 1e-4
  weight_decay: 1e-2

etc:
  phase: train # test
  resume: false
  ckpt_dir: ../results/checkpoints/baselines/resnet18/daily_x/
  ckpt_name_tag: resnet18_daily_x_ce_undersample
  ckpt_file: last.ckpt  
  ckpt_weights_only: false
  max_epochs: 50

wandb:
  name: resnet18_daily_x_ce_undersample_nasgh
  id: resnet18_daily_x_ce_undersample_nasgh
  resume: allow
  notes: resnet18
  offline: false
  tag: ["resnet18", "X", "nasgh", "daily", "cross_entropy", "undersample"] # backbone model, head type, task
