# @package _global_

data:
  train_flare_data_path: ./data/surya-bench-flare-forecasting/C2w/train_C2w_freq8.csv
  valid_flare_data_path: ./data/surya-bench-flare-forecasting/C2w/val_C2w.csv
  leaky_valid_flare_data_path: ./data/surya-bench-flare-forecasting/C2w/leaky_val_C2w.csv
  test_flare_data_path: ./data/surya-bench-flare-forecasting/C2w/test_C2w.csv
  apply_undersampling: false
  undersample_factor: 1
  seed: 1004

backbone:
  model_name: resnet18 # resnet18, resnet34, resnet50, resnet18,

loss:
  type: cross_entropy
  cross_entropy:
    class_weights: [1.0, 2.0]
  focal:
    alpha: 0.75
    gamma: 2.0
    reduction: mean
    label_smoothing: 0.2

optimizer:
  type: adamw
  lr: 1e-4
  weight_decay: 1e-2

etc:
  phase: train # test
  resume: true
  ckpt_dir: ./results/checkpoints/baselines/resnet18/8hour_c2w/
  ckpt_name_tag: resnet18_8hour_c2w_ce_nosample
  ckpt_file: last.ckpt
  ckpt_weights_only: false
  max_epochs: 50

wandb:
  name: resnet18_8hour_c2w_ce_nosample_nasgh
  id: resnet18_8hour_c2w_ce_nosample_nasgh
  resume: allow
  project: surya-flare-2hwindow-nosample
  group: resnet18
  notes: ""
  offline: false
  tag: ["resnet18", "C2w", "nasgh", "8hour", "cross_entropy", "nosampling"] # backbone model, head type, task
