# @package _global_

data:
  train_flare_data_path: ../data/surya-bench-flare-forecasting/M24w/train_M24w_freq24.csv
  valid_flare_data_path: ../data/surya-bench-flare-forecasting/M24w/val_M24w.csv
  leaky_valid_flare_data_path: ../data/surya-bench-flare-forecasting/M24w/leaky_val_M24w.csv
  test_flare_data_path: ../data/surya-bench-flare-forecasting/M24w/test_M24w.csv

head:
  pooling_type: attention_pooling
  hyper_parameters:
    in_feature: {"cls_token": 2560, "avg_pooling": 2560, "max_pooling": 2560, "attention_pooling": 2560}
    hidden_channels: [1024, 256, 1] #[256, 64, 1]

loss:
  type: cross_entropy
  cross_entropy:
    class_weights: [1.0, 2.0]
  focal:
    alpha: 0.75
    gamma: 2.0
    reduction: mean

optimizer:
  type: adamw
  lr: 1e-5
  weight_decay: 1e-2

etc:
  phase: train # test
  resume: false
  ckpt_dir: ../results/check_point/suryaflux/daily_m/
  ckpt_name_tag: flux_daily_m_crossen
  ckpt_file: last.ckpt
  ckpt_weights_only: false
  max_epochs: 50

wandb:
  name: flux_daily_m_crossen_nasgh
  id: flux_daily_m_crossen_nasgh
  resume: allow
  notes: "xray flux head"
  offline: false
  tag: ["fluxhead", "M", "daily", "nasgh", "crossen"] # backbone model, head type, task
